### ISSUE TITLE
PEP 642 v3 TODO notes

### ISSUE THREAD

**Issue by ncoghlan** [ncoghlan/peps#6]
- ~Explicitly discuss inferring equality constraints for attribute syntax in https://www.python.org/dev/peps/pep-0642/#keeping-inferred-equality-constraints and note that the presence of explicit equality constraints makes it easy to defer that feature without any loss of overall expressiveness (the only cost is an increase in verbosity for potentially common cases)~ (obsolete, all inferred patterns are being dropped in v3)

  * raised by Baptiste Carvello in https://mail.python.org/archives/list/python-dev@python.org/message/CZWZRN5J6QIJZM2C4IUOBGCWNJ7EM6QX/
- [x] Change mapping patterns and class patterns to *require* the use of `as` for value capture (but also allow ` __` to be left implicit when just capturing the value)
  * see https://mail.python.org/archives/list/python-dev@python.org/message/Q2ARJULLJG6HRCDXR4SSA7K6NLTOPUL7/ (in response to Joao Bueno and Jim Jewett)
  * also raised on Discourse in https://discuss.python.org/t/pep-642-constraint-pattern-syntax-for-structural-pattern-matching/5614/4
- [x] Check for instances of `case _:` that should be changed to `case __:` (raised on the Discourse thread)
- [x] Reference Mark Shannon's pre-PEP draft, while noting that one of the benefits of making the AST changes clearer is to better separate the surface syntax from the runtime semantics

**Comment by ncoghlan** [comment]
Working branch for these changes: https://github.com/ncoghlan/peps/tree/pep-642-v3-explicit-capture-patterns

The 2nd TODO note involves some notable changes to the surface syntax (group patterns and OR patterns turn off all inferred patterns, and class patterns default to treating classes as a "bundle of attributes", requiring an explicit trailing `/` to check against `__match_args__` instead).

**Comment by h-vetinari** [comment]
I feel this is the wrong approach. The mapping pattern should not _by default_ reassign values intransparently (and use extra syntax to _not_ bind), because that's the much more unintuitive default. From [here](https://github.com/ncoghlan/peps/blob/pep-642-v3-explicit-capture-patterns/pep-0642.rst):
```
HTTPS_PORT = 443
match expr:
    case {"port": HTTPS_PORT}:
        ... # Matches any mapping with "port", binding its value to HTTPS_PORT
    case _:
        ... # Handle the non-matching case
```
vs.
```
HTTPS_PORT = 443
match expr:
    case {"port": == HTTPS_PORT}:
        ... # Handle the case where 'expr["port"] == 443'
    case _:
        ... # Handle the non-matching case
```

Does your current update already take into account @markshannon's [considerations](https://github.com/markshannon/pattern-matching/blob/master/precise_semantics.rst) on matching semantics?

**Comment by ncoghlan** [comment]
@h-vetinari Mapping patterns aren't even the worst offender in that regard, which is why this revision pretty much stalled for the past couple of weeks - class patterns are badly flawed, as they allow "cls(ATTR=TARGET)", so `=` gets used in a construct where the target is on the *right*.

I think I have a way out, though, which is to anchor the "attribute lookup" variant of class patterns more in the mapping pattern syntax, and have the mapping syntax allow the `:` to be replaced by `==`, `is`, or `as`. That way `case {"port": HTTPS_PORT}:` becomes a syntax error, `case {"port": __}:` checks the key exists, `case {"port" == HTTPS_PORT}:` checks the value, and `case {"port" as TCP_PORT}:` binds the value.

**Comment by h-vetinari** [comment]
I have to say `case {"port" == HTTPS_PORT}:` vs. `{"port" as TCP_PORT}:` strikes me as an elegant and pythonic solution 👍 

Not sure if a third syntax (`: __`) is really necessary? Why not e.g. `== __`? I'd be even tempted to say `case {"port"}:` for the mere existence of the key, if only that wouldn't clash so hard with sets.

**Comment by ncoghlan** [comment]
@h-vetinari the ":" is needed to indicate that the item to the right is a match pattern rather than a normal Python expression. Working on the reference implementation (specifically, updating the test cases) also showed that the idea of replacing ":" with "==" or "is" wouldn't work, as it allowed cryptic nonsense like `case {0 == 1}:`. Requiring the `:` helps keep it clear which part is the key expression: `case {0: == 1}:`.

So the final result ends up looking like:

```
# Checking for a specific port in a request
HTTPS_PORT = 443
match expr:
    case {"port": == HTTPS_PORT}:
        ... # Handle the case where 'expr["port"] == 443'
    case object{.port == HTTPS_PORT}:
        ... # Handle the case where 'expr.port == 443'
    case __:
        ... # Handle the non-matching case

# Accepting host and port details in a variety of formats (2-tuple, mapping, object attributes)
match expr:
    case [as requested_host, as requested_port]:
        pass
    case {"host" as requested_host, "port" as requested_port}:
        pass
    case object{.host as requested_host, .port as requested_port}:
        pass
```

**Comment by ncoghlan** [comment]
There were indeed several PEP 642 examples that were still using `case _:`, so those have been migrated to `case __:`. The remaining instances of the PEP 634 wildcard marker are in PEP 634 examples.

**Comment by ncoghlan** [comment]
I'm in the process of publishing the PEP update for this now: https://github.com/python/peps/pull/1756
